# Generated by Django 3.0.4 on 2020-03-16 16:14

import django.contrib.gis.db.models.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='BezirkPoly',
            fields=[
                ('id', models.BigIntegerField(primary_key=True, serialize=False)),
                ('geom', django.contrib.gis.db.models.fields.MultiPolygonField(blank=True, null=True, srid=4326)),
                ('bezirksnum', models.DecimalField(blank=True, decimal_places=65535, max_digits=65535, null=True)),
                ('name', models.CharField(blank=True, max_length=254, null=True)),
            ],
            options={
                'db_table': 'bezirk_poly',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='CampingPoints',
            fields=[
                ('id', models.BigIntegerField(primary_key=True, serialize=False)),
                ('geom', django.contrib.gis.db.models.fields.PointField(blank=True, dim=3, null=True, srid=4326)),
                ('name', models.CharField(blank=True, max_length=254, null=True)),
            ],
            options={
                'db_table': 'camping_points',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='FluesseLine',
            fields=[
                ('id', models.BigIntegerField(primary_key=True, serialize=False)),
                ('geom', django.contrib.gis.db.models.fields.MultiLineStringField(blank=True, null=True, srid=4326)),
                ('objectid_g', models.DecimalField(blank=True, decimal_places=65535, max_digits=65535, null=True)),
                ('grosserflu', models.CharField(blank=True, max_length=20, null=True)),
                ('biogeo', models.CharField(blank=True, max_length=20, null=True)),
            ],
            options={
                'db_table': 'fluesse_line',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='SbbPoints',
            fields=[
                ('id', models.BigIntegerField(primary_key=True, serialize=False)),
                ('geom', django.contrib.gis.db.models.fields.MultiPointField(blank=True, null=True, srid=4326)),
                ('remark', models.CharField(blank=True, max_length=254, null=True)),
            ],
            options={
                'db_table': 'sbb_points',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='SeenPoly',
            fields=[
                ('id', models.BigIntegerField(primary_key=True, serialize=False)),
                ('geom', django.contrib.gis.db.models.fields.MultiPolygonField(blank=True, null=True, srid=4326)),
                ('id0', models.CharField(blank=True, max_length=32, null=True)),
                ('id1', models.CharField(blank=True, max_length=32, null=True)),
            ],
            options={
                'db_table': 'seen_poly',
                'managed': False,
            },
        ),
    ]
